In [1]:
import numpy as np
from sklearn.datasets import make_regression
import matplotlib.pyplot as plt

In [3]:
data = make_regression(n_samples = 1000, n_features = 1, bias=1000, noise=50 )


In [4]:
data

(array([[-0.51711778],
        [ 0.93903012],
        [ 0.90779513],
        [-0.84405695],
        [-0.20829871],
        [ 0.14196708],
        [ 0.64476016],
        [ 0.67888084],
        [ 1.24536599],
        [-0.27433505],
        [ 0.60926512],
        [-0.50716329],
        [-1.38612502],
        [ 1.61637075],
        [-0.96039108],
        [-0.37036786],
        [-0.68578179],
        [-1.20540805],
        [ 1.15052676],
        [-0.09766345],
        [ 0.42331694],
        [ 0.58312381],
        [ 0.44167144],
        [-0.16629757],
        [ 1.96235558],
        [ 0.66658087],
        [-0.85296397],
        [ 0.89422189],
        [-0.94726221],
        [ 0.86070728],
        [ 0.52101221],
        [-0.29739916],
        [-0.77537327],
        [-0.3975119 ],
        [ 2.38606804],
        [-0.38395037],
        [-2.20542116],
        [-0.81780549],
        [-0.88232673],
        [ 0.5017626 ],
        [ 0.30580582],
        [-1.48614408],
        [ 0.63489502],
        [ 0

In [5]:
x_train = data[0]
y_train = data[1]

n_data = len(x_train)
print(n_data, x_train.shape, y_train.shape)

1000 (1000, 1) (1000,)


# Hypothesis,Cost 정의

- hypothesis: x_train*w1+w0
- cost: RSS

In [6]:
# hypothesis = x_train*w1+w0
#  cost=np.sum(y_train-hypothesis)**2/n_data

In [7]:
# weight 초기화

In [8]:
w1=np.random.rand(1)
w0=np.random.rand(1)
print(w1, w0)

[0.62445978] [0.97852294]


In [9]:
# y pred 계산


In [10]:
y_pred = x_train * w1+ w0

In [11]:
x_train[0] *w1 + w0

array([0.65560368])

In [12]:
(x_train * w1 +w0)[:5]

array([[0.65560368],
       [1.56490949],
       [1.54540449],
       [0.45144332],
       [0.84844877]])

In [13]:
y_pred.shape #2차원

(1000, 1)

In [14]:
y_train.shape #1차원

(1000,)

In [15]:
#cost 계산

In [16]:
# broadcast 때문에 1차원, 1차원 빼기로 y_pred를 reshape.
(y_train - y_pred.reshape(-1))[:5]

array([965.47153407, 984.50676087, 964.42938956, 954.49198923,
       950.24662359])

In [17]:
cost = np.sum((y_train - y_pred.reshape(-1)) ** 2) / n_data

In [18]:
cost

998155.8204705553

In [19]:
# weight 업데이트

In [22]:
np.sum(x_train * (y_train-y_pred.reshape(-1)).reshape(-1, 1)) * 2 / n_data

-49.98213675066586

In [23]:
np.dot((y_train - y_pred.reshape(-1)), x_train) * 2 / n_data 

array([-49.98213675])

In [24]:
w1 -= 0.01 * (-1) * np.dot((y_train - y_pred.reshape(-1)), x_train) * 2 / n_data 

In [25]:
w0 -= (0.01) * (-1) * np.sum(y_train - y_pred.reshape(-1)) * 2 / n_data

In [26]:
w1, w0

(array([0.12463842]), array([20.93546796]))

In [ ]:
epoches = 1000